version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - ./myscript.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"