CREATE DATABASE BOOKSTORE;
USE BOOKSTORE;

CREATE TABLE TOPIC (
    TOPIC_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(TOPIC_NAME)
);

CREATE TABLE ARTICLE_TOPICS (
    TOPIC_NAME VARCHAR(50) NOT NULL,
    ARTICLE_TITLE VARCHAR(50) NOT NULL,
    WRITER_ID INTEGER NOT NULL NOT NULL,
    PRIMARY KEY(TOPIC_NAME, ARTICLE_TITLE, WRITER_ID),
    FOREIGN KEY(TOPIC_NAME) REFERENCES TOPIC(TOPIC_NAME),
    FOREIGN KEY(ARTICLE_TITLE) REFERENCES ARTICLE(ARTICLE_TITLE),
    FOREIGN KEY(WRITER_ID) REFERENCES ARTICLE(WRITER_ID)
);

CREATE TABLE WRITER(
    WRITER_ID INTEGER NOT NULL,
    NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(50),
    PRIMARY KEY(WRITER_ID)
);

CREATE TABLE ARTICLE(
     WRITER_ID INTEGER NOT NULL,
    ARTICLE_TITLE VARCHAR(50) NOT NULL,
    PRIMARY KEY(WRITER_ID, ARTICLE_TITLE),
    PUBLISHER_NAME VARCHAR(50),
    SERIES_NAME VARCHAR(50),
    ISSUE_NUMBER INTEGER NOT NULL,
    FOREIGN KEY(WRITER_ID) REFERENCES WRITER(WRITER_ID),
    FOREIGN KEY(PUBLISHER_NAME) REFERENCES MAGAZINE_ISSUE(PUBLISHER_NAME),
    FOREIGN KEY(SERIES_NAME) REFERENCES MAGAZINE_ISSUE(SERIES_NAME),
    FOREIGN KEY(ISSUE_NUMBER) REFERENCES MAGAZINE_ISSUE(ISSUE_NUMBER)
);

CREATE TABLE MAGAZINE_ISSUE(
    ISSUE_NUMBER INT NOT NULL,
    SERIES_NAME VARCHAR(50) NOT NULL,
    PUBLISHER_NAME VARCHAR(50) NOT NULL,
    CURRENT_TOTALS INT NOT NULL,
    QUANTITIES_ORDERED INT NOT NULL,
    IDEAL_AMOUNT INT NOT NULL,
    AMOUNT_SHIPPING INT NOT NULL,
    PUBLISH_DATE DATE NOT NULL,
    PRIMARY KEY(ISSUE_NUMBER, SERIES_NAME, PUBLISHER_NAME),
    FOREIGN KEY(SERIES_NAME) REFERENCES SERIES(SERIES_NAME),
    FOREIGN KEY(PUBLISHER_NAME) REFERENCES SERIES(PUBLISHER_NAME)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT NOT NULL,
    CUSTOMER_NAME VARCHAR(50),
    MAILING_ADDRESS VARCHAR(50),
    SUBSCRIPTION_TYPE VARCHAR(50),
    PHONE_NUMBER VARCHAR(50),
    EMAIL VARCHAR(50),
    PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE PUBLISHER(
	PUBLISHER_NAME VARCHAR(50) NOT NULL,
	MAILING_ADDRESS VARCHAR(50),
	PHONE_NUMBER VARCHAR(50),
	EMAIL VARCHAR(50),
	PRIMARY KEY(PUBLISHER_NAME)
);

CREATE TABLE SERIES(
    PUBLISHER_NAME VARCHAR(50) NOT NULL,
    SERIES_NAME VARCHAR(50) NOT NULL,
    PUBLICATION_FREQUENCY INT NOT NULL,
    COST_PER_BILLING_CYCLE INT NOT NULL,
    PRIMARY KEY(PUBLISHER_NAME, SERIES_NAME),
    FOREIGN KEY(PUBLISHER_NAME) REFERENCES PUBLISHER(PUBLISHER_NAME)
);

CREATE TABLE MAGAZINE_SUBSCRIPTION(
    CUSTOMER_ID INT NOT NULL,
    MAGAZINE_PUBLISHER VARCHAR(50) NOT NULL,
    SERIES_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(CUSTOMER_ID, MAGAZINE_PUBLISHER, SERIES_NAME),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(MAGAZINE_PUBLISHER) REFERENCES SERIES(PUBLISHER_NAME),
    FOREIGN KEY(SERIES_NAME) REFERENCES SERIES(SERIES_NAME)
);
